name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.x
        dune-version: 3.x

    - name: Install dependencies
      run: |
        opam install . --deps-only --with-test --with-dev-setup
        
    - name: Build
      run: opam exec -- dune build

    - name: Test
      run: opam exec -- dune exec -- run services.contract test/examples/invoke_test.example
